// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEdDxUF0fA5OGFK-93lr1yu9eXcQ2MA_Y',
    appId: '1:990664807660:android:f6ea4339010717c5e541c9',
    messagingSenderId: '990664807660',
    projectId: 'studentmove-dev',
    storageBucket: 'studentmove-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoQz5exOj7lXdkf7KqTKZwKt7QXuIfWsc',
    appId: '1:990664807660:ios:5573f0d9459c6704e541c9',
    messagingSenderId: '990664807660',
    projectId: 'studentmove-dev',
    storageBucket: 'studentmove-dev.firebasestorage.app',
    iosBundleId: 'com.example.studentmove',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-mcMMDTceUVGjPyWndZA7TsNh9vpwJ1k',
    appId: '1:990664807660:web:bc41adbebb169af2e541c9',
    messagingSenderId: '990664807660',
    projectId: 'studentmove-dev',
    authDomain: 'studentmove-dev.firebaseapp.com',
    storageBucket: 'studentmove-dev.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoQz5exOj7lXdkf7KqTKZwKt7QXuIfWsc',
    appId: '1:990664807660:ios:5573f0d9459c6704e541c9',
    messagingSenderId: '990664807660',
    projectId: 'studentmove-dev',
    storageBucket: 'studentmove-dev.firebasestorage.app',
    iosBundleId: 'com.example.studentmove',
  );

}